.TH RHINOTE 1 "March 24, 2006" "0.7.2" "User Commands"

.SH NAME
Rhinote \- virtual sticky-notes for your desktop

.SH SYNOPSIS
\fBrhinote\fR

.SH DESCRIPTION
\fBRhinote\fR is a simple program that provides virtual sticky-notes for your
desktop. It's handy for jotting down quick notes or holding copied text that
you plan to past elsewhere later.
.PP
Notes can be saved as plain text for later viewing/editing with \fBRhinote\fR
or any other text editor.
.PP
\fBRhinote\fR is designed to be "keyboard friendly", that is, every single
action is bound to a specific keystroke.

.SH KEYS
.TP
\fBCtrl-x\fR
Cut highlighted text.
.TP
\fBCtrl-c\fR
Copy highlighted text.
.TP
\fBCtrl-v\fR
Paste text from clipboard.
.TP
\fBCtrl-n\fB
Open new (blank) note.
.TP
\fBCtrl-o\fR
Open file (via a file dialog).
.TP
\fBCtrl-s\fR
Save current note.
.TP
\fBCtrl-a\fR
Save current note in a different file.
.TP
\fBCtrl-p\fR
Print current note.
.TP
\fBCtrl-h\fR
Display help window.

.SH AUTHOR
This manual page was written by Andrea Bolognani <eof@kiyuko.org> for the
Debian project (but may be used by others).
